version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      steps:
        - heroku/deploy-via-git:
          filters:
            branches:
              only: master
  publish_message:
    jobs:
      steps:
        - slack/notify:
            channel: CHANNELID
            color: '#42e2f4'
            message: This is a custom message notification
            webhook: https://hooks.slack.com/services/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