version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
  slack: circleci/slack@3.4.2

workflows:
  heroku_deploy:
    jobs:
        - heroku/deploy-via-git:
          filters:
            branches:
              only: master
  publish_message:
    jobs:
        - slack/notify:
            color: '#42e2f4'
            message: This is a custom message notification
            webhook: https://hooks.slack.com/services/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